# -*- coding: utf-8 -*-

from AddReleaseVersionStrategy import AddReleaseVersionStrategy
from AnnotateORFStrategy import AnnotateORFStrategy
from AssessDatabaseContentStrategy import AssessDatabaseContentStrategy
from BackupStrategy import BackupStrategy
from ComputeMissingInfoStrategy import ComputeMissingInfoStrategy
from ComputeRelCoordStrategy import ComputeRelCoordStrategy
from ComputeKozakContextStrategy import ComputeKozakContextStrategy
from DatabaseCheckStrategy import DatabaseCheckStrategy
from DeletionStrategy import DeletionStrategy
from FilterStrategy import FilterStrategy
from ForceInsertionStrategy import ForceInsertionStrategy
from GenerateBEDContentStrategy import GenerateBEDContentStrategy
from GenerateBEDFileStrategy import GenerateBEDFileStrategy
from GenerateTrackDbFileStrategy import GenerateTrackDbFileStrategy
from GenerateGFFFileStrategy import GenerateGFFFileStrategy
from GenerateFastaFileStrategy import GenerateFastaFileStrategy
from GenerateStatFilesStrategy import GenerateStatFilesStrategy
from InsertionStrategy import InsertionStrategy
from LiftOverStrategy import LiftOverStrategy
from MergeStrategy import MergeStrategy
from RestoreStrategy import RestoreStrategy
from ResumeMergeStrategy import ResumeMergeStrategy
